set_property SRC_FILE_INFO {cfile:{C:/Users/lauro/OneDrive/Desktop/Midterm 2 code new/user_gpio_ip_user_constrain.xdc} rfile:{../../../../Users/lauro/OneDrive/Desktop/Midterm 2 code new/user_gpio_ip_user_constrain.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports LED[0]]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports LED[1]]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports LED[2]]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports LED[3]]
